default_platform(:ios)

platform :ios do
  def install_profile
    sigh(
      app_identifier: ENV['APP_IDENTIFIER'],
      provisioning_name: "SOAPJournal AppStore",
      output_path: "./profiles",
      filename: "AppStore.mobileprovision",
      force: true
    )
    profile_path = sh("ls -t /Users/runner/work/SOAPJournal/SOAPJournal/profiles/AppStore.mobileprovision | head -n 1").strip
    decoded_plist = "/tmp/profile.plist"
    sh("security cms -D -i '#{profile_path}' > #{decoded_plist}")
    profile_uuid = sh("/usr/libexec/PlistBuddy -c 'Print :UUID' #{decoded_plist}").strip
  
    destination = "#{ENV['HOME']}/Library/MobileDevice/Provisioning Profiles/#{profile_uuid}.mobileprovision"
    sh("mkdir -p '#{File.dirname(destination)}'")
    sh("cp '#{profile_path}' '#{destination}'")
  end
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_CONTENT'],
      in_house: false
    )
    install_profile

    build_app(
      scheme: "SOAPJournal",
      export_method: "app-store",
      configuration: "Release",
      export_options: {
        provisioningProfiles: {
          ENV['APP_IDENTIFIER'] => "SOAPJournal AppStore"
        },
        signingCertificate: "Apple Distribution",
        signingStyle: "manual",
        teamID: ENV['TEAM_ID']
      }
    )

    upload_to_testflight
  end
end
