default_platform(:ios)

platform :ios do
  lane :fetch_profile do
    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_CONTENT']
    )
  
    sigh(
      app_identifier: ENV['APP_IDENTIFIER'],
      provisioning_name: "Actions",
      force: true,
    )
  
    sh("mkdir -p ~/Library/MobileDevice/Provisioning\\ Profiles")
    sh("cp ./profiles/AppStore.mobileprovision ~/Library/MobileDevice/Provisioning\\ Profiles/")
  end
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_CONTENT'],
      in_house: false
    )

    build_app(
      scheme: "SOAPJournal",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          ENV['APP_IDENTIFIER'] => "Actions"
        }
      }
    )

    upload_to_testflight
  end
end
