name: iOS TestFlight Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # 手動で実行できるようにする

jobs:
  deploy_to_testflight:
    name: Build and Deploy to TestFlight
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true

      - name: Set up Xcode
        run: |
          xcodebuild -version
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Upload to TestFlight
        env:
          # App Store Connect APIキー (必須)
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          
          # Apple ID (APIキーでの認証時はオプショナル)
          APPLE_ID: ${{ secrets.APPLE_ID }}
          
          # 以下はAPIから自動取得されるようになったため、手動設定時のみ使用
          TEAM_ID: ${{ secrets.TEAM_ID }}
          APPLE_APP_ID: ${{ secrets.APPLE_APP_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          
          # カスタムバンドルIDを使用する場合のみ設定
          # BUNDLE_IDENTIFIER: ${{ secrets.BUNDLE_IDENTIFIER }}
        run: |
          bundle exec fastlane beta
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            ./build/*.ipa
            ./build/*.dSYM.zip
            
      - name: Post build status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ ビルドとTestFlightへのアップロードが成功しました！"
            echo "TestFlight経由でアプリをテストできます。"
          else
            echo "❌ ビルドが失敗しました。ログを確認してください。"
          fi
