name: iOS Build and Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: |
          xcodebuild -version

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install Ruby and Bundler
        run: |
          brew install ruby
          gem install bundler -N

      - name: Install gems
        run: bundle install --jobs 4 --retry 3

      - name: Install dependencies
        run: bundle exec fastlane install_dependencies

      - name: Run tests
        run: bundle exec fastlane test

      - name: Build and Archive
        run: bundle exec fastlane build_and_archive

  release:
    name: Release to TestFlight
    needs: build
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main' # mainブランチへのpush時のみ実行
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: |
          xcodebuild -version

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install Ruby and Bundler
        run: |
          brew install ruby
          gem install bundler -N

      - name: Install gems
        run: bundle install --jobs 4 --retry 3

      - name: Install dependencies
        run: bundle exec fastlane install_dependencies

      - name: Upload to TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # matchを使用する場合
        run: bundle exec fastlane beta
