name: iOS TestFlight Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # 手動で実行できるようにする

jobs:
  deploy_to_testflight:
    name: Build and Deploy to TestFlight
    runs-on: macos-latest
    env:
      APP_IDENTIFIER: com.steamside-tree.soapjournal
      APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
      APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
      P12_FILE: ${{ secrets.P12_FILE }}
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Show Xcode version
        run: |
          xcodebuild -version
          xcrun simctl list runtimes

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
          
      - name: Set up OpenSSL
        run: |
          brew update
          brew upgrade openssl

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Prepare certificates
        run: |
          echo "$P12_FILE" | base64 --decode > signing.p12
          security create-keychain -p build123 build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p build123 build.keychain
          security import signing.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k build123 build.keychain

      - name: Generate API key JSON
        run: |
          echo '{
            "key_id": "${APP_STORE_CONNECT_API_KEY_ID}",
            "issuer_id": "${APP_STORE_CONNECT_API_KEY_ISSUER_ID}",
            "key": "${APP_STORE_CONNECT_API_KEY_CONTENT}"
          }' > AuthKey.json
      - name: Run Fastlane
        run: bundle exec fastlane beta
